In [1]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np

# Display all columns
pd.set_option('display.max_columns', None)

# Display wider tables
pd.set_option('display.width', 1000)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("../data/raw/emdat_disasters_1970_2021.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
# First 5 rows

df.head()

          Dis No  Year  Seq Glide Disaster Group Disaster Subgroup Disaster Type  Disaster Subtype Disaster Subsubtype Event Name     Country  ISO                     Region Continent            Location Origin Associated Dis Associated Dis2 OFDA Response Appeal Declaration  Aid Contribution  Dis Mag Value Dis Mag Scale Latitude Longitude Local Time River Basin  Start Year  Start Month  Start Day  End Year  End Month  End Day  Total Deaths  No Injured  No Affected  No Homeless  Total Affected  Reconstruction Costs ('000 US$)  Insured Damages ('000 US$)  Total Damages ('000 US$)        CPI Adm Level Admin1 Code Admin2 Code Geo Locations
0  1970-0013-ARG  1970   13   NaN        Natural      Hydrological         Flood               NaN                 NaN        NaN   Argentina  ARG              South America  Americas             Mendoza    NaN            NaN             NaN           NaN    NaN         NaN               NaN            NaN           Km2      NaN       NaN        NaN         NaN        1970          1.0        4.0      1970        1.0      4.0          36.0         NaN          NaN          NaN             NaN                              NaN                         NaN                   25000.0  15.001282       NaN         NaN         NaN           NaN
1  1970-0109-AUS  1970  109   NaN        Natural    Meteorological         Storm  Tropical cyclone                 NaN        Ada   Australia  AUS  Australia and New Zealand   Oceania          Queensland    NaN            NaN             NaN           NaN    NaN         NaN               NaN            NaN           Kph      NaN       NaN        NaN         NaN        1970          1.0        NaN      1970        1.0      NaN          13.0         NaN          NaN          NaN             NaN                              NaN                         NaN                   72475.0  15.001282       NaN         NaN         NaN           NaN
2  1970-0044-BEN  1970   44   NaN        Natural      Hydrological         Flood               NaN                 NaN        NaN       Benin  BEN             Western Africa    Africa      Atacora region    NaN            NaN             NaN           Yes    NaN         NaN               NaN            NaN           Km2      NaN       NaN        NaN         NaN        1970          9.0        NaN      1970        9.0      NaN           NaN         NaN          NaN          NaN             NaN                              NaN                         NaN                     200.0  15.001282       NaN         NaN         NaN           NaN
3  1970-0063-BGD  1970   63   NaN        Natural    Meteorological         Storm  Tropical cyclone                 NaN        NaN  Bangladesh  BGD              Southern Asia      Asia  Khulna, Chittagong    NaN            NaN             NaN           Yes    NaN         NaN               NaN            NaN           Kph      NaN       NaN        NaN         NaN        1970         11.0       12.0      1970       11.0     12.0      300000.0         NaN    3648000.0          NaN       3648000.0                              NaN                         NaN                   86400.0  15.001282       NaN         NaN         NaN           NaN
4  1970-0026-BGD  1970   26   NaN        Natural    Meteorological         Storm               NaN                 NaN        NaN  Bangladesh  BGD              Southern Asia      Asia                 NaN    NaN            NaN             NaN           NaN    NaN         NaN               NaN            NaN           Kph      NaN       NaN        NaN         NaN        1970          4.0       13.0      1970        4.0     13.0          17.0         NaN        110.0          NaN           110.0                              NaN                         NaN                       NaN  15.001282       NaN         NaN         NaN           NaN

In [5]:
# Last 5 rows

df.tail()

              Dis No  Year  Seq           Glide Disaster Group Disaster Subgroup Disaster Type Disaster Subtype Disaster Subsubtype  Event Name                                 Country  ISO           Region Continent                                           Location       Origin Associated Dis Associated Dis2 OFDA Response Appeal Declaration  Aid Contribution  Dis Mag Value Dis Mag Scale Latitude Longitude Local Time                 River Basin  Start Year  Start Month  Start Day  End Year  End Month  End Day  Total Deaths  No Injured  No Affected  No Homeless  Total Affected  Reconstruction Costs ('000 US$)  Insured Damages ('000 US$)  Total Damages ('000 US$)  CPI Adm Level                                Admin1 Code  Admin2 Code                                      Geo Locations
14639  2021-0449-YEM  2021  449  FL-2021-000110        Natural      Hydrological         Flood              NaN                 NaN         NaN                                   Yemen  YEM     Western Asia      Asia  Dhamar, Amran, Al Mahwit, Marib, Ibb, Sana’a C...  Heavy rains            NaN             NaN           NaN    NaN         NaN               NaN            NaN           Km2      NaN       NaN        NaN                         NaN        2021          7.0       16.0      2021        8.0      7.0          11.0         NaN      67980.0          NaN         67980.0                              NaN                         NaN                       NaN  NaN       NaN                                        NaN          NaN                                                NaN
14640  2021-0075-ZAF  2021   75             NaN        Natural      Hydrological         Flood              NaN                 NaN         NaN                            South Africa  ZAF  Southern Africa    Africa  Mpumalanga Province, Free State Province and t...  Heavy rains            NaN             NaN           NaN    NaN         NaN               NaN            NaN           Km2      NaN       NaN        NaN                         NaN        2021          2.0        1.0      2021        2.0     15.0          31.0         NaN        400.0          NaN           400.0                              NaN                         NaN                   75000.0  NaN       1;2               2707;77311;77312;77313;77315  77364;77367  Free State, KwaZulu-Natal, Limpopo, Mpumalanga...
14641  2021-0599-COD  2021  599  EP-2021-000138        Natural        Biological      Epidemic    Viral disease                 NaN  Meningitis  Congo (the Democratic Republic of the)  COD    Middle Africa    Africa                                    Tshopo province          NaN            NaN             NaN           NaN    NaN         Yes               NaN            NaN    Vaccinated      NaN       NaN        NaN                         NaN        2021          9.0        7.0      2021        9.0     13.0         131.0       301.0          NaN          NaN           301.0                              NaN                         NaN                       NaN  NaN       NaN                                        NaN          NaN                                                NaN
14642  2021-0020-SRB  2021   20             NaN        Natural      Hydrological         Flood              NaN                 NaN         NaN                                  Serbia  SRB  Southern Europe    Europe  Zitoradja (Toplicki), Doljevac (Nisavski) , Di...  Heavy rains            NaN             NaN           NaN    NaN         Yes               NaN            NaN           Km2      NaN       NaN        NaN                         NaN        2021          1.0       11.0      2021        1.0     12.0           NaN         NaN         22.0          NaN            22.0                              NaN                         NaN                       NaN  NaN         1  25374;25378;25379;25380;25383;25386;25397          NaN  Jablanicki, Kosovski, Kosovsko-mitrovatski, Ko...
14643  2021-0481-SSD  2021  481             NaN        Natural      Hydrological         Flood              NaN                 NaN         NaN                             South Sudan  SSD  Northern Africa    Africa  Mayendit County (Unity); Ayod, Fangak Counties...  Heavy rains            NaN             NaN           NaN    NaN         NaN               NaN            NaN           Km2      NaN       NaN        NaN  Nile, Lol and Sobat rivers        2021          5.0        NaN      2021       10.0      7.0           7.0         NaN     500000.0          NaN        500000.0                              NaN                         NaN                       NaN  NaN       NaN                                        NaN          NaN                                                NaN

In [6]:
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows : 14644
Columns : 47

In [7]:
df.columns.tolist()

['Dis No',
 'Year',
 'Seq',
 'Glide',
 'Disaster Group',
 'Disaster Subgroup',
 'Disaster Type',
 'Disaster Subtype',
 'Disaster Subsubtype',
 'Event Name',
 'Country',
 'ISO',
 'Region',
 'Continent',
 'Location',
 'Origin',
 'Associated Dis',
 'Associated Dis2',
 'OFDA Response',
 'Appeal',
 'Declaration',
 'Aid Contribution',
 'Dis Mag Value',
 'Dis Mag Scale',
 'Latitude',
 'Longitude',
 'Local Time',
 'River Basin',
 'Start Year',
 'Start Month',
 'Start Day',
 'End Year',
 'End Month',
 'End Day',
 'Total Deaths',
 'No Injured',
 'No Affected',
 'No Homeless',
 'Total Affected',
 "Reconstruction Costs ('000 US$)",
 "Insured Damages ('000 US$)",
 "Total Damages ('000 US$)",
 'CPI',
 'Adm Level',
 'Admin1 Code',
 'Admin2 Code',
 'Geo Locations']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14644 entries, 0 to 14643
Data columns (total 47 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Dis No                           14644 non-null  object
 1   Year                             14644 non-null  int64
 2   Seq                              14644 non-null  int64
 3   Glide                            1581 non-null   object
 4   Disaster Group                   14644 non-null  object
 5   Disaster Subgroup                14644 non-null  object
 6   Disaster Type                    14644 non-null  object
 7   Disaster Subtype                 11897 non-null  object
 8   Disaster Subsubtype              1044 non-null   object
 9   Event Name                       3645 non-null   object
 10  Country                          14644 non-null  object
 11  ISO                              14644 non-null  object
 12  Region                           14644 non-null  object
 13  Continent                        14644 non-null  object
 14  Location                         13298 non-null  object
 15  Origin                           3780 non-null   object
 16  Associated Dis                   3232 non-null   object
 17  Associated Dis2                  698 non-null    object
 18  OFDA Response                    1450 non-null   object
 19  Appeal                           2440 non-null   object
 20  Declaration                      3127 non-null   object
 21  Aid Contribution                 677 non-null    float64
 22  Dis Mag Value                    4569 non-null   float64
 23  Dis Mag Scale                    13571 non-null  object
 24  Latitude                         2331 non-null   object
 25  Longitude                        2335 non-null   object
 26  Local Time                       765 non-null    object
 27  River Basin                      1285 non-null   object
 28  Start Year                       14644 non-null  int64
 29  Start Month                      14376 non-null  float64
 30  Start Day                        11577 non-null  float64
 31  End Year                         14644 non-null  int64
 32  End Month                        14095 non-null  float64
 33  End Day                          11650 non-null  float64
 34  Total Deaths                     10199 non-null  float64
 35  No Injured                       3651 non-null   float64
 36  No Affected                      8846 non-null   float64
 37  No Homeless                      2249 non-null   float64
 38  Total Affected                   11041 non-null  float64
 39  Reconstruction Costs ('000 US$)  31 non-null     float64
 40  Insured Damages ('000 US$)       1094 non-null   float64
 41  Total Damages ('000 US$)         4863 non-null   float64
 42  CPI                              14329 non-null  float64
 43  Adm Level                        7855 non-null   object
 44  Admin1 Code                      4581 non-null   object
 45  Admin2 Code                      3965 non-null   object
 46  Geo Locations                    7855 non-null   object
dtypes: float64(15), int64(4), object(28)
memory usage: 5.3+ MB

In [9]:
df.describe()

               Year           Seq  Aid Contribution  Dis Mag Value    Start Year   Start Month     Start Day      End Year     End Month       End Day   Total Deaths    No Injured   No Affected   No Homeless  Total Affected  Reconstruction Costs ('000 US$)  Insured Damages ('000 US$)  Total Damages ('000 US$)           CPI
count  14644.000000  14644.000000      6.770000e+02   4.569000e+03  14644.000000  14376.000000  11577.000000  14644.000000  14095.000000  11650.000000   10199.000000  3.651000e+03  8.846000e+03  2.249000e+03    1.104100e+04                     3.100000e+01                1.094000e+03              4.863000e+03  14329.000000
mean    2001.596422    731.604958      1.254136e+05   5.093532e+04   2001.606323      6.411241     15.207912   2001.655763      6.549273     15.792618     361.813119  2.486686e+03  8.889099e+05  7.229559e+04    7.277392e+05                     2.392251e+06                7.999424e+05              7.746866e+05     68.762532
std       12.538572   1912.021531      2.997875e+06   3.211007e+05     12.535872      3.393997      8.964592     12.537387      3.351351      8.872079    6495.045853  3.402404e+04  8.680288e+06  5.271422e+05    7.851210e+06                     5.229397e+06                3.060283e+06              4.901266e+06     21.429182
min     1970.000000      1.000000      1.000000e+00  -5.700000e+01   1970.000000      1.000000      1.000000   1970.000000      1.000000      1.000000       1.000000  1.000000e+00  1.000000e+00  3.000000e+00    1.000000e+00                     8.400000e+01                3.400000e+01              2.000000e+00     15.001282
25%     1993.000000    130.000000      1.750000e+02   7.000000e+00   1993.000000      4.000000      7.000000   1993.000000      4.000000      8.000000       5.000000  1.200000e+01  1.200000e+03  5.140000e+02    6.320000e+02                     1.200000e+04                5.000000e+04              1.000000e+04     55.816107
50%     2003.000000    304.000000      7.210000e+02   1.800000e+02   2003.000000      7.000000     15.000000   2003.000000      7.000000     16.000000      16.000000  5.000000e+01  1.000000e+04  3.000000e+03    5.736000e+03                     1.940000e+05                1.725000e+05              7.100000e+04     69.500473
75%     2012.000000    503.000000      3.511000e+03   1.515000e+04   2012.000000      9.000000     23.000000   2012.000000      9.000000     24.000000      50.000000  2.000000e+02  8.855250e+04  1.600000e+04    5.600000e+04                     1.520376e+06                5.000000e+05              3.500000e+05     86.912465
max     2021.000000   9881.000000      7.800000e+07   1.302587e+07   2021.000000     12.000000     31.000000   2021.000000     12.000000     31.000000  300000.000000  1.800000e+06  3.300000e+08  1.585000e+07    3.300000e+08                     2.500000e+07                6.000000e+07              2.100000e+08    100.000000

In [10]:
df.describe(include='object')

               Dis No           Glide Disaster Group Disaster Subgroup Disaster Type Disaster Subtype Disaster Subsubtype Event Name                         Country    ISO         Region Continent Location       Origin                 Associated Dis                Associated Dis2 OFDA Response Appeal Declaration Dis Mag Scale Latitude Longitude Local Time   River Basin Adm Level Admin1 Code Admin2 Code                               Geo Locations
count           14644            1581          14644             14644         14644            11897                1044       3645                           14644  14644          14644     14644    13298         3780                           3232                            698          1450   2440        3127         13571     2331      2335        765          1285      7855        4581        3965                                        7855
unique          14644            1086              1                 6            14               27                  12       1488                             228    228             23         5    11995          660                             30                             29             1      2           2             5     2091      2095        608          1213         3        3434        3445                                        6354
top     1970-0013-ARG  CW-2012-000006        Natural      Hydrological         Flood   Riverine flood             Tornado    Cholera  United States of America (the)    USA  Southern Asia      Asia    North  Heavy rains  Slide (land, mud, snow, rock)  Slide (land, mud, snow, rock)           Yes     No          No           Km2    3.295    95.982      05:15  Mekong river         1         925       13306  Administrative unit not available (Adm1).
freq                1              29          14644              5985          5272             2633                 264        481                             949    949           1849      5793       37         1489                           1213                            268          1450   2240        2213          6409       12        12          4             9      3890          56           9                                          93

In [11]:
missing = df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

Reconstruction Costs ('000 US$)    14613
Aid Contribution                   13967
Associated Dis2                    13946
Local Time                         13879
Disaster Subsubtype                13600
Insured Damages ('000 US$)         13550
River Basin                        13359
OFDA Response                      13194
Glide                              13063
No Homeless                        12395
Latitude                           12313
Longitude                          12309
Appeal                             12204
Declaration                        11517
Associated Dis                     11412
Event Name                         10999
No Injured                         10993
Origin                             10864
Admin2 Code                        10679
Dis Mag Value                      10075
Admin1 Code                        10063
Total Damages ('000 US$)            9781
Adm Level                           6789
Geo Locations                       6789
No Affected                         5798
Total Deaths                        4445
Total Affected                      3603
Start Day                           3067
End Day                             2994
Disaster Subtype                    2747
Location                            1346
Dis Mag Scale                       1073
End Month                            549
CPI                                  315
Start Month                          268
dtype: int64

In [12]:
missing_percent = (
    df.isnull().sum() / len(df) * 100
).sort_values(ascending=False)

missing_percent[missing_percent > 0]

Reconstruction Costs ('000 US$)    99.788309
Aid Contribution                   95.376946
Associated Dis2                    95.233543
Local Time                         94.776017
Disaster Subsubtype                92.870800
Insured Damages ('000 US$)         92.529364
River Basin                        91.225075
OFDA Response                      90.098334
Glide                              89.203769
No Homeless                        84.642174
Latitude                           84.082218
Longitude                          84.054903
Appeal                             83.337886
Declaration                        78.646545
Associated Dis                     77.929527
Event Name                         75.109260
No Injured                         75.068287
Origin                             74.187380
Admin2 Code                        72.924064
Dis Mag Value                      68.799508
Admin1 Code                        68.717564
Total Damages ('000 US$)           66.791860
Adm Level                          46.360284
Geo Locations                      46.360284
No Affected                        39.593007
Total Deaths                       30.353728
Total Affected                     24.603933
Start Day                          20.943731
End Day                            20.445234
Disaster Subtype                   18.758536
Location                            9.191478
Dis Mag Scale                       7.327233
End Month                           3.748976
CPI                                 2.151052
Start Month                         1.830101
dtype: float64

In [13]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [14]:
df.dtypes

Dis No                              object
Year                                 int64
Seq                                  int64
Glide                               object
Disaster Group                      object
Disaster Subgroup                   object
Disaster Type                       object
Disaster Subtype                    object
Disaster Subsubtype                 object
Event Name                          object
Country                             object
ISO                                 object
Region                              object
Continent                           object
Location                            object
Origin                              object
Associated Dis                      object
Associated Dis2                     object
OFDA Response                       object
Appeal                              object
Declaration                         object
Aid Contribution                   float64
Dis Mag Value                      float64
Dis Mag Scale                       object
Latitude                            object
Longitude                           object
Local Time                          object
River Basin                         object
Start Year                           int64
Start Month                        float64
Start Day                          float64
End Year                             int64
End Month                          float64
End Day                            float64
Total Deaths                       float64
No Injured                         float64
No Affected                        float64
No Homeless                        float64
Total Affected                     float64
Reconstruction Costs ('000 US$)    float64
Insured Damages ('000 US$)         float64
Total Damages ('000 US$)           float64
CPI                                float64
Adm Level                           object
Admin1 Code                         object
Admin2 Code                         object
Geo Locations                       object
dtype: object

In [15]:
df.nunique().sort_values()

Disaster Group                         1
OFDA Response                          1
Appeal                                 2
Declaration                            2
Adm Level                              3
Dis Mag Scale                          5
Continent                              5
Disaster Subgroup                      6
Start Month                           12
Disaster Subsubtype                   12
End Month                             12
Disaster Type                         14
Region                                23
Disaster Subtype                      27
Associated Dis2                       29
Reconstruction Costs ('000 US$)       29
Associated Dis                        30
End Day                               31
Start Day                             31
CPI                                   51
End Year                              52
Start Year                            52
Year                                  52
Country                              228
ISO                                  228
Insured Damages ('000 US$)           362
Aid Contribution                     556
Local Time                           608
Origin                               660
Total Deaths                         710
No Injured                           713
No Homeless                          840
Glide                               1086
River Basin                         1213
Seq                                 1265
Event Name                          1488
Total Damages ('000 US$)            1519
Dis Mag Value                       1860
Latitude                            2091
Longitude                           2095
Admin1 Code                         3434
Admin2 Code                         3445
No Affected                         3492
Total Affected                      4901
Geo Locations                       6354
Location                           11995
Dis No                             14644
dtype: int64

In [18]:
# Create a copy of the original dataset
df_clean = df.copy()

In [19]:
# Display all column names

for i, column in enumerate(df_clean.columns, start=1):
    print(f"{i}. {column}")

1. Dis No
2. Year
3. Seq
4. Glide
5. Disaster Group
6. Disaster Subgroup
7. Disaster Type
8. Disaster Subtype
9. Disaster Subsubtype
10. Event Name
11. Country
12. ISO
13. Region
14. Continent
15. Location
16. Origin
17. Associated Dis
18. Associated Dis2
19. OFDA Response
20. Appeal
21. Declaration
22. Aid Contribution
23. Dis Mag Value
24. Dis Mag Scale
25. Latitude
26. Longitude
27. Local Time
28. River Basin
29. Start Year
30. Start Month
31. Start Day
32. End Year
33. End Month
34. End Day
35. Total Deaths
36. No Injured
37. No Affected
38. No Homeless
39. Total Affected
40. Reconstruction Costs ('000 US$)
41. Insured Damages ('000 US$)
42. Total Damages ('000 US$)
43. CPI
44. Adm Level
45. Admin1 Code
46. Admin2 Code
47. Geo Locations

In [20]:
# Check duplicate records
print("Duplicate Rows:", df_clean.duplicated().sum())

Duplicate Rows: 0

In [21]:
missing = df_clean.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

Reconstruction Costs ('000 US$)    14613
Aid Contribution                   13967
Associated Dis2                    13946
Local Time                         13879
Disaster Subsubtype                13600
Insured Damages ('000 US$)         13550
River Basin                        13359
OFDA Response                      13194
Glide                              13063
No Homeless                        12395
Latitude                           12313
Longitude                          12309
Appeal                             12204
Declaration                        11517
Associated Dis                     11412
Event Name                         10999
No Injured                         10993
Origin                             10864
Admin2 Code                        10679
Dis Mag Value                      10075
Admin1 Code                        10063
Total Damages ('000 US$)            9781
Adm Level                           6789
Geo Locations                       6789
No Affected                         5798
Total Deaths                        4445
Total Affected                      3603
Start Day                           3067
End Day                             2994
Disaster Subtype                    2747
Location                            1346
Dis Mag Scale                       1073
End Month                            549
CPI                                  315
Start Month                          268
dtype: int64