In [1]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/raw/emdat_disasters_1970_2021.csv")

print(df.shape)

(14644, 47)

In [3]:
df.head()

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,Country,ISO,Region,Continent,Location,Origin,Associated Dis,Associated Dis2,OFDA Response,Appeal,Declaration,Aid Contribution,Dis Mag Value,Dis Mag Scale,Latitude,Longitude,Local Time,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No Injured,No Affected,No Homeless,Total Affected,Reconstruction Costs ('000 US$),Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1970-0013-ARG,1970,13,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,Argentina,ARG,South America,Americas,Mendoza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Km2,NaN,NaN,NaN,NaN,1970,1.0,4.0,1970,1.0,4.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,25000.0,15.001282,NaN,NaN,NaN,NaN
1,1970-0109-AUS,1970,109,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,Ada,Australia,AUS,Australia and New Zealand,Oceania,Queensland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kph,NaN,NaN,NaN,NaN,1970,1.0,NaN,1970,1.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,72475.0,15.001282,NaN,NaN,NaN,NaN
2,1970-0044-BEN,1970,44,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,Benin,BEN,Western Africa,Africa,Atacora region,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,Km2,NaN,NaN,NaN,NaN,1970,9.0,NaN,1970,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.0,15.001282,NaN,NaN,NaN,NaN
3,1970-0063-BGD,1970,63,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,Bangladesh,BGD,Southern Asia,Asia,"Khulna, Chittagong",NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,Kph,NaN,NaN,NaN,NaN,1970,11.0,12.0,1970,11.0,12.0,300000.0,NaN,3648000.0,NaN,3648000.0,NaN,NaN,86400.0,15.001282,NaN,NaN,NaN,NaN
4,1970-0026-BGD,1970,26,NaN,Natural,Meteorological,Storm,NaN,NaN,NaN,Bangladesh,BGD,Southern Asia,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kph,NaN,NaN,NaN,NaN,1970,4.0,13.0,1970,4.0,13.0,17.0,NaN,110.0,NaN,110.0,NaN,NaN,NaN,15.001282,NaN,NaN,NaN,NaN

In [4]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.info()

Rows : 14644
Columns : 47
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14644 entries, 0 to 14643
Data columns (total 47 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Dis No                           14644 non-null  object
 1   Year                             14644 non-null  int64
 2   Seq                              14644 non-null  int64
 3   Glide                            1581 non-null   object
 4   Disaster Group                   14644 non-null  object
 5   Disaster Subgroup                14644 non-null  object
 6   Disaster Type                    14644 non-null  object
 7   Disaster Subtype                 11897 non-null  object
 8   Disaster Subsubtype              1044 non-null   object
 9   Event Name                       3645 non-null   object
 10  Country                          14644 non-null  object
 11  ISO                              14644 non-null  object
 12  Region                           14644 non-null  object
 13  Continent                        14644 non-null  object
 14  Location                         13298 non-null  object
 15  Origin                           3780 non-null   object
 16  Associated Dis                   3232 non-null   object
 17  Associated Dis2                  698 non-null    object
 18  OFDA Response                    1450 non-null   object
 19  Appeal                           2440 non-null   object
 20  Declaration                      3127 non-null   object
 21  Aid Contribution                 677 non-null    float64
 22  Dis Mag Value                    4569 non-null   float64
 23  Dis Mag Scale                    13571 non-null  object
 24  Latitude                         2331 non-null   object
 25  Longitude                        2335 non-null   object
 26  Local Time                       765 non-null    object
 27  River Basin                      1285 non-null   object
 28  Start Year                       14644 non-null  int64
 29  Start Month                      14376 non-null  float64
 30  Start Day                        11577 non-null  float64
 31  End Year                         14644 non-null  int64
 32  End Month                        14095 non-null  float64
 33  End Day                          11650 non-null  float64
 34  Total Deaths                     10199 non-null  float64
 35  No Injured                       3651 non-null   float64
 36  No Affected                      8846 non-null   float64
 37  No Homeless                      2249 non-null   float64
 38  Total Affected                   11041 non-null  float64
 39  Reconstruction Costs ('000 US$)  31 non-null     float64
 40  Insured Damages ('000 US$)       1094 non-null   float64
 41  Total Damages ('000 US$)         4863 non-null   float64
 42  CPI                              14329 non-null  float64
 43  Adm Level                        7855 non-null   object
 44  Admin1 Code                      4581 non-null   object
 45  Admin2 Code                      3965 non-null   object
 46  Geo Locations                    7855 non-null   object
dtypes: float64(15), int64(4), object(28)
memory usage: 5.3+ MB

In [6]:
missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

missing[missing > 0]

Reconstruction Costs ('000 US$)    14613
Aid Contribution                   13967
Associated Dis2                    13946
Local Time                         13879
Disaster Subsubtype                13600
Insured Damages ('000 US$)         13550
River Basin                        13359
OFDA Response                      13194
Glide                              13063
No Homeless                        12395
Latitude                           12313
Longitude                          12309
Appeal                             12204
Declaration                        11517
Associated Dis                     11412
Event Name                         10999
No Injured                         10993
Origin                             10864
Admin2 Code                        10679
Dis Mag Value                      10075
Admin1 Code                        10063
Total Damages ('000 US$)            9781
Adm Level                           6789
Geo Locations                       6789
No Affected                         5798
Total Deaths                        4445
Total Affected                      3603
Start Day                           3067
End Day                             2994
Disaster Subtype                    2747
Location                            1346
Dis Mag Scale                       1073
End Month                            549
CPI                                  315
Start Month                          268
dtype: int64

In [5]:
df.describe()

,Year,Seq,Aid Contribution,Dis Mag Value,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No Injured,No Affected,No Homeless,Total Affected,Reconstruction Costs ('000 US$),Insured Damages ('000 US$),Total Damages ('000 US$),CPI
count,14644.000000,14644.000000,6.770000e+02,4.569000e+03,14644.000000,14376.000000,11577.000000,14644.000000,14095.000000,11650.000000,10199.000000,3.651000e+03,8.846000e+03,2.249000e+03,1.104100e+04,3.100000e+01,1.094000e+03,4.863000e+03,14329.000000
mean,2001.596422,731.604958,1.254136e+05,5.093532e+04,2001.606323,6.411241,15.207912,2001.655763,6.549273,15.792618,361.813119,2.486686e+03,8.889099e+05,7.229559e+04,7.277392e+05,2.392251e+06,7.999424e+05,7.746866e+05,68.762532
std,12.538572,1912.021531,2.997875e+06,3.211007e+05,12.535872,3.393997,8.964592,12.537387,3.351351,8.872079,6495.045853,3.402404e+04,8.680288e+06,5.271422e+05,7.851210e+06,5.229397e+06,3.060283e+06,4.901266e+06,21.429182
min,1970.000000,1.000000,1.000000e+00,-5.700000e+01,1970.000000,1.000000,1.000000,1970.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00,8.400000e+01,3.400000e+01,2.000000e+00,15.001282
25%,1993.000000,130.000000,1.750000e+02,7.000000e+00,1993.000000,4.000000,7.000000,1993.000000,4.000000,8.000000,5.000000,1.200000e+01,1.200000e+03,5.140000e+02,6.320000e+02,1.200000e+04,5.000000e+04,1.000000e+04,55.816107
50%,2003.000000,304.000000,7.210000e+02,1.800000e+02,2003.000000,7.000000,15.000000,2003.000000,7.000000,16.000000,16.000000,5.000000e+01,1.000000e+04,3.000000e+03,5.736000e+03,1.940000e+05,1.725000e+05,7.100000e+04,69.500473
75%,2012.000000,503.000000,3.511000e+03,1.515000e+04,2012.000000,9.000000,23.000000,2012.000000,9.000000,24.000000,50.000000,2.000000e+02,8.855250e+04,1.600000e+04,5.600000e+04,1.520376e+06,5.000000e+05,3.500000e+05,86.912465
max,2021.000000,9881.000000,7.800000e+07,1.302587e+07,2021.000000,12.000000,31.000000,2021.000000,12.000000,31.000000,300000.000000,1.800000e+06,3.300000e+08,1.585000e+07,3.300000e+08,2.500000e+07,6.000000e+07,2.100000e+08,100.000000

In [7]:
df.describe(include="object")

,Dis No,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,Country,ISO,Region,Continent,Location,Origin,Associated Dis,Associated Dis2,OFDA Response,Appeal,Declaration,Dis Mag Scale,Latitude,Longitude,Local Time,River Basin,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
count,14644,1581,14644,14644,14644,11897,1044,3645,14644,14644,14644,14644,13298,3780,3232,698,1450,2440,3127,13571,2331,2335,765,1285,7855,4581,3965,7855
unique,14644,1086,1,6,14,27,12,1488,228,228,23,5,11995,660,30,29,1,2,2,5,2091,2095,608,1213,3,3434,3445,6354
top,1970-0013-ARG,CW-2012-000006,Natural,Hydrological,Flood,Riverine flood,Tornado,Cholera,United States of America (the),USA,Southern Asia,Asia,North,Heavy rains,"Slide (land, mud, snow, rock)","Slide (land, mud, snow, rock)",Yes,No,No,Km2,3.295,95.982,05:15,Mekong river,1,925,13306,Administrative unit not available (Adm1).
freq,1,29,14644,5985,5272,2633,264,481,949,949,1849,5793,37,1489,1213,268,1450,2240,2213,6409,12,12,4,9,3890,56,9,93

In [8]:
unique = pd.DataFrame({
    "Unique Values": df.nunique()
})

unique.sort_values(
    by="Unique Values",
    ascending=False
)

                                 Unique Values
Dis No                                   14644
Location                                 11995
Geo Locations                             6354
Total Affected                            4901
No Affected                               3492
Admin2 Code                               3445
Admin1 Code                               3434
Longitude                                 2095
Latitude                                  2091
Dis Mag Value                             1860
Total Damages ('000 US$)                  1519
Event Name                                1488
Seq                                       1265
River Basin                               1213
Glide                                     1086
No Homeless                                840
No Injured                                 713
Total Deaths                               710
Origin                                     660
Local Time                                 608
Aid Contribution                           556
Insured Damages ('000 US$)                 362
Country                                    228
ISO                                        228
Start Year                                  52
End Year                                    52
Year                                        52
CPI                                         51
End Day                                     31
Start Day                                   31
Associated Dis                              30
Reconstruction Costs ('000 US$)             29
Associated Dis2                             29
Disaster Subtype                            27
Region                                      23
Disaster Type                               14
Start Month                                 12
End Month                                   12
Disaster Subsubtype                         12
Disaster Subgroup                            6
Continent                                    5
Dis Mag Scale                                5
Adm Level                                    3
Appeal                                       2
Declaration                                  2
Disaster Group                               1
OFDA Response                                1

In [9]:
df["Disaster Type"].value_counts()

Disaster Type
Flood                    5272
Storm                    4005
Epidemic                 1436
Earthquake               1137
Landslide                 713
Drought                   685
Extreme temperature       584
Wildfire                  452
Volcanic activity         222
Insect infestation         93
Mass movement (dry)        41
Glacial lake outburst       2
Impact                      1
Animal accident             1
Name: count, dtype: int64

In [10]:
top_disasters = (
    df["Disaster Type"]
      .value_counts()
      .head(10)
)

top_disasters

Disaster Type
Flood                   5272
Storm                   4005
Epidemic                1436
Earthquake              1137
Landslide                713
Drought                  685
Extreme temperature      584
Wildfire                 452
Volcanic activity        222
Insect infestation        93
Name: count, dtype: int64

In [11]:
df["Country"].nunique()

228

In [12]:
df["Country"].value_counts().head(20)

Country
United States of America (the)    949
China                             906
India                             658
Philippines (the)                 612
Indonesia                         528
Bangladesh                        317
Japan                             272
Mexico                            262
Viet Nam                          241
Australia                         240
Brazil                            227
Pakistan                          213
Iran (Islamic Republic of)        205
Afghanistan                       200
Colombia                          188
Peru                              178
Russian Federation (the)          173
France                            173
Thailand                          155
Italy                             147
Name: count, dtype: int64

In [13]:
df["Continent"].value_counts()

Continent
Asia        5793
Americas    3519
Africa      2812
Europe      1858
Oceania      662
Name: count, dtype: int64

In [14]:
df["Region"].value_counts()

Region
Southern Asia                1849
South-Eastern Asia           1809
Eastern Asia                 1578
South America                1163
Eastern Africa               1128
Northern America             1075
Western Africa                758
Central America               751
Southern Europe               577
Eastern Europe                535
Caribbean                     530
Western Europe                492
Middle Africa                 421
Western Asia                  416
Australia and New Zealand     312
Northern Africa               305
Melanesia                     232
Northern Europe               207
Southern Africa               200
Central Asia                  141
Polynesia                      75
Russian Federation             47
Micronesia                     43
Name: count, dtype: int64

In [15]:
print("Minimum Year :", df["Year"].min())

print("Maximum Year :", df["Year"].max())

Minimum Year : 1970
Maximum Year : 2021

In [16]:
yearly = (
    df.groupby("Year")
      .size()
      .reset_index(name="Disaster_Count")
)

yearly.head()

   Year  Disaster_Count
0  1970              82
1  1971              63
2  1972              63
3  1973              65
4  1974              72

In [17]:
impact = df[
    [
        "Total Deaths",
        "No Injured",
        "No Affected",
        "No Homeless",
        "Total Affected"
    ]
]

impact.describe()

        Total Deaths    No Injured   No Affected   No Homeless  Total Affected
count   10199.000000  3.651000e+03  8.846000e+03  2.249000e+03    1.104100e+04
mean      361.813119  2.486686e+03  8.889099e+05  7.229559e+04    7.277392e+05
std      6495.045853  3.402404e+04  8.680288e+06  5.271422e+05    7.851210e+06
min         1.000000  1.000000e+00  1.000000e+00  3.000000e+00    1.000000e+00
25%         5.000000  1.200000e+01  1.200000e+03  5.140000e+02    6.320000e+02
50%        16.000000  5.000000e+01  1.000000e+04  3.000000e+03    5.736000e+03
75%        50.000000  2.000000e+02  8.855250e+04  1.600000e+04    5.600000e+04
max    300000.000000  1.800000e+06  3.300000e+08  1.585000e+07    3.300000e+08

In [18]:
df["Total Damages ('000 US$)"].describe()

count    4.863000e+03
mean     7.746866e+05
std      4.901266e+06
min      2.000000e+00
25%      1.000000e+04
50%      7.100000e+04
75%      3.500000e+05
max      2.100000e+08
Name: Total Damages ('000 US$), dtype: float64

In [20]:
#Visualization 1: Number of Disasters Over Time
#Business Question

#How has the frequency of natural disasters changed between 1970 and 2021?

import plotly.express as px

# Count disasters by year
yearly_disasters = (
    df.groupby("Year")
      .size()
      .reset_index(name="Number_of_Disasters")
)

fig = px.line(
    yearly_disasters,
    x="Year",
    y="Number_of_Disasters",
    title="Global Natural Disasters by Year (1970–2021)",
    markers=True
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    xaxis_title="Year",
    yaxis_title="Number of Disasters",
    height=600
)

fig.show()

In [21]:
#Visualization 2: Top 10 Disaster Types
#Business Question

#Which natural disasters occur most frequently?

disaster_type = (
    df["Disaster Type"]
      .value_counts()
      .head(10)
      .reset_index()
)

disaster_type.columns = [
    "Disaster Type",
    "Count"
]

fig = px.bar(
    disaster_type,
    x="Disaster Type",
    y="Count",
    color="Count",
    text="Count",
    title="Top 10 Most Frequent Disaster Types"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=600
)

fig.show()

In [22]:
#Visualization 3: Disasters by Continent

continent = (
    df["Continent"]
      .value_counts()
      .reset_index()
)

continent.columns = [
    "Continent",
    "Count"
]

fig = px.pie(
    continent,
    values="Count",
    names="Continent",
    title="Distribution of Natural Disasters by Continent"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=650
)

fig.show()

In [23]:
#Visualization 4: Top 15 Countries
country = (
    df["Country"]
      .value_counts()
      .head(15)
      .reset_index()
)

country.columns = [
    "Country",
    "Count"
]

fig = px.bar(
    country,
    x="Count",
    y="Country",
    orientation="h",
    color="Count",
    title="Top 15 Countries with the Highest Number of Recorded Disasters"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=700
)

fig.show()

In [ ]:
#Visualization 5: Hierarchy of Natural Disaster Types
treemap_data = (
    df.groupby(["Disaster Subgroup", "Disaster Type"])
      .size()
      .reset_index(name="Count")
)

fig = px.treemap(
    treemap_data,
    path=["Disaster Subgroup", "Disaster Type"],
    values="Count",
    title="Hierarchy of Natural Disaster Types"
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    height=700
)

fig.show()